services:
  - type: web
    name: spirit-of-wood-backend
    runtime: docker
    dockerContext: ./project/back-end
    dockerfilePath: ./project/back-end/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: ADMIN_SEED_EMAIL
        sync: false
      - key: ADMIN_SEED_PASSWORD
        sync: false
