app.name=spirit-of-wood
app.version=1.0.0

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

admin.seed.email=${ADMIN_SEED_EMAIL:}
admin.seed.password=${ADMIN_SEED_PASSWORD:}
